import { StudentProfile, StudentOutcome } from './types';

export const MOCK_STUDENTS: StudentProfile[] = [
  {
    id: "STU001",
    name: "Alex Johnson",
    lastUpdated: "2026-02-25",
    data: {
      ageAtEnrollment: 19,
      gender: "Male",
      nationality: "Domestic",
      displaced: false,
      educationalSpecialNeeds: false,
      debtor: false,
      tuitionFeesUpToDate: true,
      scholarshipHolder: true,
      parentalEducation: "Higher",
      unitsEnrolled1st: 6,
      unitsApproved1st: 6,
      unitsEvaluated1st: 6,
      unitsWithoutEvaluations1st: 0,
      gradeAverage1st: 16.5,
      unemploymentRate: 7.2,
      inflationRate: 1.2,
      gdp: 2.1,
    },
    prediction: {
      outcome: StudentOutcome.GRADUATE,
      confidence: 0.92,
      riskScore: 5,
      probabilities: {
        [StudentOutcome.DROPOUT]: 0.05,
        [StudentOutcome.ENROLLED]: 0.03,
        [StudentOutcome.GRADUATE]: 0.92,
      },
      reasoning: "Excellent academic performance and financial stability.",
      recommendations: ["Consider for honors program", "Peer mentoring role"],
    }
  },
  {
    id: "STU002",
    name: "Maria Garcia",
    lastUpdated: "2026-02-26",
    data: {
      ageAtEnrollment: 24,
      gender: "Female",
      nationality: "International",
      displaced: true,
      educationalSpecialNeeds: false,
      debtor: true,
      tuitionFeesUpToDate: false,
      scholarshipHolder: false,
      parentalEducation: "Secondary",
      unitsEnrolled1st: 6,
      unitsApproved1st: 2,
      unitsEvaluated1st: 6,
      unitsWithoutEvaluations1st: 2,
      gradeAverage1st: 10.2,
      unemploymentRate: 12.5,
      inflationRate: 3.5,
      gdp: -0.5,
    },
    prediction: {
      outcome: StudentOutcome.DROPOUT,
      confidence: 0.85,
      riskScore: 82,
      probabilities: {
        [StudentOutcome.DROPOUT]: 0.82,
        [StudentOutcome.ENROLLED]: 0.15,
        [StudentOutcome.GRADUATE]: 0.03,
      },
      reasoning: "High financial stress combined with low approval rates and displacement status.",
      recommendations: ["Urgent financial aid review", "Academic counseling session", "Language support services"],
    }
  },
  {
    id: "STU003",
    name: "Liam Smith",
    lastUpdated: "2026-02-24",
    data: {
      ageAtEnrollment: 21,
      gender: "Male",
      nationality: "Domestic",
      displaced: false,
      educationalSpecialNeeds: false,
      debtor: false,
      tuitionFeesUpToDate: true,
      scholarshipHolder: false,
      parentalEducation: "Primary",
      unitsEnrolled1st: 6,
      unitsApproved1st: 4,
      unitsEvaluated1st: 6,
      unitsWithoutEvaluations1st: 0,
      gradeAverage1st: 12.8,
      unemploymentRate: 9.0,
      inflationRate: 2.0,
      gdp: 1.0,
    },
    prediction: {
      outcome: StudentOutcome.ENROLLED,
      confidence: 0.65,
      riskScore: 45,
      probabilities: {
        [StudentOutcome.DROPOUT]: 0.45,
        [StudentOutcome.ENROLLED]: 0.45,
        [StudentOutcome.GRADUATE]: 0.10,
      },
      reasoning: "Moderate performance but showing signs of struggle in core units.",
      recommendations: ["Study group placement", "Mid-term check-in"],
    }
  },
  {
    id: "STU004",
    name: "Chloe Chen",
    lastUpdated: "2026-02-27",
    data: {
      ageAtEnrollment: 18,
      gender: "Female",
      nationality: "International",
      displaced: false,
      educationalSpecialNeeds: false,
      debtor: false,
      tuitionFeesUpToDate: true,
      scholarshipHolder: false,
      parentalEducation: "Higher",
      unitsEnrolled1st: 6,
      unitsApproved1st: 5,
      unitsEvaluated1st: 6,
      unitsWithoutEvaluations1st: 0,
      gradeAverage1st: 14.5,
      unemploymentRate: 8.5,
      inflationRate: 1.8,
      gdp: 1.2,
    },
    prediction: {
      outcome: StudentOutcome.GRADUATE,
      confidence: 0.75,
      riskScore: 15,
      probabilities: {
        [StudentOutcome.DROPOUT]: 0.15,
        [StudentOutcome.ENROLLED]: 0.10,
        [StudentOutcome.GRADUATE]: 0.75,
      },
      reasoning: "Solid performance and stable background.",
      recommendations: ["Encourage extracurricular participation"],
    }
  }
];
